var cid="60";
var pid="170";

if(localStorage["is_reg_push"]==undefined||localStorage["is_reg_push"]=="")localStorage["is_reg_push"]=false;if(localStorage["not_read_count"]==undefined||localStorage["not_read_count"]=="")localStorage["not_read_count"]=0;if(localStorage["pushmsg_data"]==undefined)localStorage["pushmsg_data"]="";if(localStorage["pushmsg_tmp"]==undefined)localStorage["pushmsg_tmp"]="";if(localStorage["pushmsg_bugnum"]==undefined)localStorage["pushmsg_bugnum"]="";var pushNotification;
if(typeof cordova==undefined)var CORDOVA_LIBARY_LOAD=false;else var CORDOVA_LIBARY_LOAD=true;function DR(){push_start()}
function push_start(){try{pushNotification=window.plugins.pushNotification;if(device.platform=="android"||device.platform=="Android")pushNotification.register(successHandler,errorHandler,{"senderID":"754846154787","ecb":"onNotificationGCM"});else pushNotification.register(tokenHandler,errorHandler,{"badge":"true","sound":"true","alert":"true","ecb":"onNotificationAPN"})}catch(err){txt="\u6709\u4e00\u500b\u932f\u8aa4 \n\n";txt+=err.message;alert(txt)}}
function tokenHandler(result){localStorage["is_reg_push"]=true}function successHandler(result){localStorage["is_reg_push"]=true}function errorHandler(error){alert(error)}function onNotificationAPN(e){if(e.alert){$("#pushul").append("<li>push-notification: "+e.alert+"</li>");navigator.notification.alert(e.alert)}if(e.sound){var snd=new Media(e.sound);snd.play()}if(e.badge)pushNotification.setApplicationIconBadgeNumber(successHandler,e.badge)}
function onNotificationGCM(e){switch(e.event){case "registered":if(e.regid.length>0){var url="http://www.app4u.tw/sendpush/reice_regid";$.post(url,{regid:e.regid,cid:cid,pid:pid},function(data){if(data.status=="y"||data.status=="n3")localStorage["is_reg_push"]=true},"json")}break;case "message":var msg="<li>"+e.payload.message+"</li>";if(e.foreground){if(msg!=localStorage["pushmsg_bugnum"]){var aid=$.mobile.activePage.attr("id");if(aid=="pushmsg"){$("#pushmsgul").prepend(msg);$("#pushmsgul").listview("refresh");
localStorage["pushmsg_data"]=$("#pushmsgcc").html()}else{localStorage["pushmsg_tmp"]=msg+localStorage["pushmsg_tmp"];localStorage["not_read_count"]++;if(aid=="page1"){$("#pushmsgcount").html(localStorage["not_read_count"]);$("#pushmsgcount").css("display","")}}}localStorage["pushmsg_bugnum"]=msg;var my_media=new Media("/android_asset/www/"+e.soundname);my_media.play()}else if(e.coldstart){if(localStorage["pushmsg_bugnum"]!=msg){localStorage["pushmsg_tmp"]=msg+localStorage["pushmsg_tmp"];localStorage["not_read_count"]++}localStorage["pushmsg_bugnum"]=
msg}else{if(localStorage["pushmsg_bugnum"]!=msg){localStorage["pushmsg_tmp"]=msg+localStorage["pushmsg_tmp"];localStorage["not_read_count"]++}localStorage["pushmsg_bugnum"]=msg}break;case "error":break;default:break}}if(CORDOVA_LIBARY_LOAD)document.addEventListener("deviceready",DR,true);